"""Create Event table and add event_id to Race

Revision ID: 7b06de80cac3
Revises: 28041ad6bdcc
Create Date: 2025-06-25 14:55:49.002458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b06de80cac3'
down_revision = '28041ad6bdcc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('province', sa.String(length=100), nullable=True),
    sa.Column('discipline', sa.String(length=50), nullable=True),
    sa.Column('distance', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=512), nullable=True),
    sa.Column('is_good_for_debutants', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('is_challenging', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('has_great_views', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('has_good_atmosphere', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('is_world_qualifier', sa.Boolean(), server_default='f', nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_discipline'), ['discipline'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_distance'), ['distance'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_province'), ['province'], unique=False)

    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'events', ['event_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('event_id')

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_province'))
        batch_op.drop_index(batch_op.f('ix_events_name'))
        batch_op.drop_index(batch_op.f('ix_events_id'))
        batch_op.drop_index(batch_op.f('ix_events_distance'))
        batch_op.drop_index(batch_op.f('ix_events_discipline'))

    op.drop_table('events')
    # ### end Alembic commands ###
