"""Add LeagueParticipant and LeagueInvitationCode tables

Revision ID: 9c07452b1e95
Revises: 43904c745596
Create Date: 2025-07-01 21:58:28.399007

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql # O el dialecto apropiado si no es PostgreSQL

# revision identifiers, used by Alembic.
revision = '9c07452b1e95'
down_revision = '43904c745596' # Asegúrate que este es el ID de la revisión anterior correcta
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('league_invitation_codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=36), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('league_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'league_id', name='_user_league_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('league_participants')
    op.drop_table('league_invitation_codes')
    # ### end Alembic commands ###
