"""Add status to events table

Revision ID: a1b2c3d4e5f6
Revises: 7b06de80cac3
Create Date: 2024-06-30 14:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6' # Nuevo ID de revisión
down_revision = '7b06de80cac3' # El ID de la última migración existente
branch_labels = None
depends_on = None

# Definición del Enum para PostgreSQL
event_status_enum = sa.Enum('PENDIENTE', 'VALIDADO', 'RECHAZADO', name='eventstatus')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Crear el tipo ENUM en PostgreSQL
    event_status_enum.create(op.get_bind(), checkfirst=True)

    # Añadir la columna 'status' a la tabla 'events'
    # Permitir NULLs inicialmente para evitar problemas con datos existentes si los hubiera.
    op.add_column('events', sa.Column('status', event_status_enum, nullable=True))

    # Actualizar las filas existentes para que tengan un valor por defecto 'VALIDADO'.
    # Si los eventos existentes deben ser PENDIENTE, cambiar 'VALIDADO' por 'PENDIENTE'.
    op.execute("UPDATE events SET status = 'VALIDADO' WHERE status IS NULL")

    # Finalmente, hacer que la columna 'status' sea NOT NULL y establecer el server_default.
    op.alter_column('events', 'status',
                    existing_type=event_status_enum,
                    nullable=False,
                    server_default='PENDIENTE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'status')

    # Eliminar el tipo ENUM de PostgreSQL
    event_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
