"""Add OfficialAnswer and OfficialAnswerMultipleChoiceOption models

Revision ID: 0800364b7fcf
Revises: ad6f31c3c99f
Create Date: 2025-06-15 23:07:44.454163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0800364b7fcf'
down_revision = 'ad6f31c3c99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is problematic and redundant. Neutralizing its operations.
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # This migration is problematic and redundant. Neutralizing its operations.
    pass
    # ### end Alembic commands ###
