"""Add OfficialAnswer and OfficialAnswerMultipleChoiceOption models

Revision ID: 0800364b7fcf
Revises: ad6f31c3c99f
Create Date: 2025-06-15 23:07:44.454163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0800364b7fcf'
down_revision = 'ad6f31c3c99f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'question_id', name='_race_question_uc')
    )
    op.create_table('official_answer_multiple_choice_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_answer_id', sa.Integer(), nullable=False),
    sa.Column('question_option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['official_answer_id'], ['official_answers.id'], ),
    sa.ForeignKeyConstraint(['question_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_answer_id', 'question_option_id', name='_official_answer_option_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_answer_multiple_choice_options')
    op.drop_table('official_answers')
    # ### end Alembic commands ###
