"""Add slider question type fields

Revision ID: 20231027100000
Revises: 20250613131338
Create Date: 2023-10-27 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20231027100000'
down_revision = '20250613131338' # Set based on the latest known migration before this one
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Actual table names from models.py are 'questions', 'official_answers', 'user_answers'
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider_unit', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('slider_min_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slider_max_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slider_step', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slider_points_exact', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('slider_threshold_partial', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slider_points_partial', sa.Integer(), nullable=True))

    with op.batch_alter_table('official_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_slider_value', sa.Float(), nullable=True))

    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slider_answer_value', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Actual table names from models.py are 'questions', 'official_answers', 'user_answers'
    with op.batch_alter_table('user_answers', schema=None) as batch_op:
        batch_op.drop_column('slider_answer_value')

    with op.batch_alter_table('official_answers', schema=None) as batch_op:
        batch_op.drop_column('correct_slider_value')

    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_column('slider_points_partial')
        batch_op.drop_column('slider_threshold_partial')
        batch_op.drop_column('slider_points_exact')
        batch_op.drop_column('slider_step')
        batch_op.drop_column('slider_max_value')
        batch_op.drop_column('slider_min_value')
        batch_op.drop_column('slider_unit')
    # ### end Alembic commands ###
