"""Add is_general column to races table

Revision ID: 20250613131338
Revises: 0e32f8bb4c5d
Create Date: 2025-06-13 13:14:23.933225218

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '20250613131338' # Will be replaced by filename part by user
down_revision = '0e32f8bb4c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_general', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('races', schema=None) as batch_op:
        batch_op.drop_column('is_general')
    # ### end Alembic commands ###
