"""Add OfficialAnswer and OfficialAnswerMultipleChoiceOption models

Revision ID: 21627c8fdfc6
Revises: 35f50c000e41
Create Date: 2025-06-14 22:08:16.576572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21627c8fdfc6'
down_revision = '35f50c000e41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('race_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    # sa.Column('created_by_id', sa.Integer(), nullable=False), # Removed as per model alignment
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ), # Removed
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'question_id', name='_race_question_uc') # Changed unique constraint
    )
    op.create_table('official_answer_multiple_choice_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_answer_id', sa.Integer(), nullable=False),
    sa.Column('question_option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['official_answer_id'], ['official_answers.id'], ),
    sa.ForeignKeyConstraint(['question_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_answer_id', 'question_option_id', name='_official_answer_option_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_answer_multiple_choice_options')
    # Reverting to the original structure of this specific migration, not the problematic one.
    op.drop_table('official_answers') # This will drop the table with the new structure.
    # To be fully correct, the downgrade should recreate the table as it was *before* this specific migration.
    # However, for the purpose of moving forward to a clean state, just dropping is acceptable here.
    # If we were to make this truly reversible to its previous state (before this edit), we'd recreate:
    # op.create_table('official_answers',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('question_id', sa.Integer(), nullable=False),
    # sa.Column('answer_text', sa.Text(), nullable=True),
    # sa.Column('selected_option_id', sa.Integer(), nullable=True),
    # sa.Column('created_by_id', sa.Integer(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    # sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    # sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('question_id')
    # )
    # ### end Alembic commands ###
