"""add_code_and_description_to_roles_table

Revision ID: 4057948044a4
Revises: 0002
Create Date: 2025-06-03 09:45:11.367691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4057948044a4'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('roles_name_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('roles_name_key'), ['name'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('description')
        batch_op.drop_column('code')

    # ### end Alembic commands ###
