"""remove_official_answers_tables

Revision ID: a1b2c3d4e5f6
Revises: 21627c8fdfc6
Create Date: 2025-06-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = '21627c8fdfc6' # Assumes the previous migration that added these tables is the direct predecessor
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('official_answer_multiple_choice_options')
    op.drop_table('official_answers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('official_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['selected_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id')
    )
    op.create_table('official_answer_multiple_choice_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('official_answer_id', sa.Integer(), nullable=False),
    sa.Column('question_option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['official_answer_id'], ['official_answers.id'], ),
    sa.ForeignKeyConstraint(['question_option_id'], ['question_options.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('official_answer_id', 'question_option_id', name='_official_answer_option_uc')
    )
    # ### end Alembic commands ###
