"""Add is_deleted to Race model

Revision ID: abcdef123456
Revises: 20250613131338
Create Date: 2023-11-16 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcdef123456'
down_revision = '20250613131338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto-generated by Alembic - START ###
    # Este bloque será reemplazado por el script que generes con 'flask db migrate'
    op.add_column('races', sa.Column('is_deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto-generated by Alembic - START ###
    # Este bloque será reemplazado por el script que generes con 'flask db migrate'
    op.drop_column('races', 'is_deleted')
    # ### end Alembic commands ###
